"""Add APIKey and update AuditLog

Revision ID: 3e43bf6a651f
Revises: 39ac1e823fed
Create Date: 2026-05-31 22:56:11.619466

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3e43bf6a651f"
down_revision: str | None = "39ac1e823fed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("business_id", sa.UUID(), nullable=True))
    op.add_column("audit_logs", sa.Column("resource_type", sa.String(length=50), nullable=True))
    op.add_column("audit_logs", sa.Column("before_value", sa.JSON(), nullable=True))
    op.add_column("audit_logs", sa.Column("after_value", sa.JSON(), nullable=True))
    op.add_column("audit_logs", sa.Column("severity", sa.String(length=20), nullable=False, server_default="INFO"))
    op.create_index(op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_business_id"), "audit_logs", ["business_id"], unique=False)
    op.create_index(op.f("ix_audit_logs_module"), "audit_logs", ["module"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_logs_module"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_business_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_column("audit_logs", "severity")
    op.drop_column("audit_logs", "after_value")
    op.drop_column("audit_logs", "before_value")
    op.drop_column("audit_logs", "resource_type")
    op.drop_column("audit_logs", "business_id")
    # ### end Alembic commands ###
