"""add ai models

Revision ID: 953eed12f59b
Revises: 05dfc82d6d7f
Create Date: 2026-06-01 00:07:45.140006

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "953eed12f59b"
down_revision: str | None = "05dfc82d6d7f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_memories",
        sa.Column("business_id", sa.UUID(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("context_key", sa.String(length=255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_memories_business_id"), "ai_memories", ["business_id"], unique=False)
    op.create_index(op.f("ix_ai_memories_context_key"), "ai_memories", ["context_key"], unique=False)
    op.create_index(op.f("ix_ai_memories_id"), "ai_memories", ["id"], unique=False)
    op.create_index(op.f("ix_ai_memories_user_id"), "ai_memories", ["user_id"], unique=False)
    op.create_table(
        "prompt_templates",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompt_templates_id"), "prompt_templates", ["id"], unique=False)
    op.create_index(op.f("ix_prompt_templates_name"), "prompt_templates", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prompt_templates_name"), table_name="prompt_templates")
    op.drop_index(op.f("ix_prompt_templates_id"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    op.drop_index(op.f("ix_ai_memories_user_id"), table_name="ai_memories")
    op.drop_index(op.f("ix_ai_memories_id"), table_name="ai_memories")
    op.drop_index(op.f("ix_ai_memories_context_key"), table_name="ai_memories")
    op.drop_index(op.f("ix_ai_memories_business_id"), table_name="ai_memories")
    op.drop_table("ai_memories")
    # ### end Alembic commands ###
