"""add index to invoices business_id

Revision ID: d8bda6ba8e6e
Revises: 71148ca9b15e
Create Date: 2026-06-01 01:28:31.133439

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8bda6ba8e6e"
down_revision: str | None = "71148ca9b15e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_invoices_business_id"), "invoices", ["business_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoices_business_id"), table_name="invoices")
    # ### end Alembic commands ###
