"""create system settings table

Revision ID: ebda6a0fb237
Revises: d8bda6ba8e6e
Create Date: 2026-06-08 23:51:08.462578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebda6a0fb237'
down_revision: Union[str, None] = 'd8bda6ba8e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('global_mfa_requirement', sa.Boolean(), nullable=False),
    sa.Column('strict_password_complexity', sa.Boolean(), nullable=False),
    sa.Column('idle_session_timeout', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_sessions', sa.Integer(), nullable=False),
    sa.Column('admin_ip_whitelist', sa.Text(), nullable=False),
    sa.Column('global_rate_limit', sa.Integer(), nullable=False),
    sa.Column('allowed_cors_domains', sa.String(length=255), nullable=False),
    sa.Column('active_signing_keys_count', sa.Integer(), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('operating_region', sa.String(length=100), nullable=False),
    sa.Column('local_currency', sa.String(length=50), nullable=False),
    sa.Column('system_timezone', sa.String(length=50), nullable=False),
    sa.Column('base_tax_rate', sa.Float(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('new_registrations', sa.Boolean(), nullable=False),
    sa.Column('debug_mode', sa.Boolean(), nullable=False),
    sa.Column('system_log_retention_days', sa.Integer(), nullable=False),
    sa.Column('database_quota_gb', sa.Integer(), nullable=False),
    sa.Column('database_used_gb', sa.Integer(), nullable=False),
    sa.Column('media_storage_quota_gb', sa.Integer(), nullable=False),
    sa.Column('media_storage_used_gb', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_settings_id'), 'system_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_settings_id'), table_name='system_settings')
    op.drop_table('system_settings')
    # ### end Alembic commands ###
